# Generated by Django 4.2.28 on 2026-03-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_userprofile_minimize_sidebar'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaconfiguration',
            name='aa_state',
            field=models.ForeignKey(blank=True, help_text='Only contracts belonging to corporations in this state will be shown.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.state'),
        ),
    ]
