# Generated by Django 4.2.28 on 2026-03-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('logistica', '0004_contractthreshold_solar_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractthreshold',
            options={'ordering': ['solar_system__name', 'title'], 'permissions': [('manage_contract_thresholds', 'Can manage contract thresholds')]},
        ),
        migrations.AddField(
            model_name='logisticaconfiguration',
            name='esi_character',
            field=models.ForeignKey(blank=True, help_text='Character whose token is used for ESI structure lookups. Must have the esi-universe.read_structures.v1 scope.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter'),
        ),
    ]
