# Generated by Django 4.2.28 on 2026-05-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0018_blueprintactivity_blueprintactivityproduct_and_more'),
        ('logistica', '0005_esi_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractthreshold',
            name='solar_system',
            field=models.ForeignKey(help_text='Solar system the contract must originate from.', on_delete=django.db.models.deletion.CASCADE, to='eve_sde.solarsystem'),
        ),
    ]
